### ISSUE TITLE
Tag cluster with custom name

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria-ec2-ansible#13]
To disambiguate nodes when running multiple clusters under the same username/region, add a new "name" parameter to myria-deploy that:
- Adds the name as a prefix to the instance name (e.g., `myria-deploy --name foo` -> name tag="foo-bhaynes-useast1-myria-myria")
- Adds a new "cluster-name" tag (`myria-deploy --name foo` -> cluster-name="foo")

**Comment by senderista** [comment]
Agree that the cluster name (when we add the corresponding param to the script) should be exposed as tag(s). I'd like to revisit the instance name convention though (which I think is only useful for viewing in the console). Do you think concatenating the key pair name and profile is useful? Should we be using the IAM user name instead of the profile? Shouldn't we leave the region out since it's implicit in the console view? Or do we need to ensure that cluster names are unique across regions (not sure how we do that without maintaining our own metadata, unless we check tags in all regions whenever deploying a new cluster)?

**Comment by BrandonHaynes** [comment]
Something like [cluster-name]-[IAM name]-[coordinator | workerN] would cover most uses cases; I think this is similar to how Starcluster named nodes.  Attaching the keypair name as a separate tag would probably be useful for some debugging-related edge cases.  Region is useless, and I don't foresee a use case that would require cluster names to be unique across regions.

**Comment by senderista** [comment]
Fixed by https://github.com/uwescience/myria-ec2-ansible/commit/c27393e54c0a65c59ee5b072bac5e56b70d6a6eb
