### ISSUE TITLE
When updating, myria-cluster should fail if recompilation fails

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria-ec2-ansible#43]
When I ran a cluster update, the MyriaX recompile failed (likely due to unrelated memory issues).  Ideally there should be a check on whether recompilation succeeded before proceeding to the next stage of the update process.

**Comment by senderista** [comment]
I've tested this by introducing a syntax error into the Myria source, and it works as expected (i.e., the Myria compile task fails). The problem seems to be when the Linux OOM killer terminates the Java compiler (or the gradle wrapper). The process should still return a nonzero exit code to the shell (143), and Ansible should fail the task. I had a hard time trying to repro this scenario, so I'll just add a check to ensure that the Myria jar is present after the Ansible `compile` task is complete (it should be deleted at the beginning by the Gradle `clean` task).

**Comment by BrandonHaynes** [comment]
Awesome, thanks Tobin!  I'll let you know if I encounter this again, but it sounds like this should take care of it.

**Comment by senderista** [comment]
Actually I'm not sure how your scenario is possible with the current code. The first thing the Myria compile task does is delete the build directories (`gradle clean`), and we test for existence of the Myria binary before running this task again. If the build command returns success, it must mean that the Myria binary exists; if it returns failure, then the binary was already deleted and couldn't have been recreated. At any rate the compile task should run again on the next retry. If you can still repro this issue, could you run `myria-cluster update` with the `--verbose` switch and paste the console output?

**Comment by BrandonHaynes** [comment]
I wound up SSHing into the demo cluster and compiling manually; it took 3-4 attempts before I was able to get it to build successfully.  It's possible that myria-cluster did retry but gave up after n attempts.  I'll reopen if I encounter again.

**Comment by senderista** [comment]
Would it be helpful to have some option to `myria-cluster update` for compiling Myria locally and uploading the jar?

**Comment by BrandonHaynes** [comment]
Possibly, but let's see if this occurs again before spending more time on it.  I'm not aware of it having happened to anyone else.
